# HW5 ver 7
# HW6 ver 8
# HW6 part 2 ver 9
# HW6 part 3 ver 10
# HW7 11
application: raj-julha-cs253
version: 11
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:


# - url: /blog/post(/?[0-9]+)
#  script: blog.app

- url: /blog/showpost(/?.*)
  script: blog.app


- url: /blog
  script: blog.app

- url: /blog/newpost
  script: blog.app

- url: /blog/\.json
  script: blog.app

- url: /blog/flush
  script: blog.app

- url: /blog/post(/?[0-9]+\.json)
  script: blog.app

# - url: /blog/post(/?[0-9]+)
#  script: blog.app

- url: /blog(/?[0-9]+)
  script: blog.app

- url: /blog(/(?:[a-zA-Z0-9_-]+/?)*)
  script: blog.app

# should be last
- url: /blog/.*
  script: raj-julha-cs253.application 


#- url: /weke(/(?:[a-zA-Z0-9_-]+/?)*)
#  script: wiki.app

- url: /wiki/signup
  script: raj-julha-cs253.application

- url: /wiki/welcome
  script: raj-julha-cs253.application

- url: /wiki/login
  script: raj-julha-cs253.application

- url: /wiki/logout
  script: raj-julha-cs253.application


- url: /wiki/.*
  script: wiki.app

# should be last
- url: /.*
  script: raj-julha-cs253.application 
